name: Maven Test and Publish Allure Report

on:
  workflow_call:
    inputs:
      token:
        description: 'Token for authentication'
        required: true
        type: string

  workflow_dispatch: # Allows manual triggering
  repository_dispatch:
    types: [trigger-workflow]  # Event type to listen for

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ./target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ inputs.token }}  # Use the token input
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
