# File: .github/workflows/maven_test_and_publish.yml

name: Maven Test and Slack Notification v2.0

on:
  workflow_dispatch:
    # Manually trigger the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
     - uses: actions/checkout@v3
    
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

     - name: Run Maven tests
       run: mvn -B test
         

     - name: Archive test results
       if: always()
       uses: actions/upload-artifact@v2
       with:
          name: surefire-reports
          path: target/surefire-reports

  slack_notification:
    name: Notify Slack on test results
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Extract test counts
        id: extract-counts
        run: |
          surefire_report_path="target/surefire-reports/*.xml"
          total_tests=$(xml sel -t -v "count(/testsuite/testcase)" "$surefire_report_path")
          passed_tests=$(xml sel -t -v "count(/testsuite/testcase[@status='passed'])" "$surefire_report_path")
          failed_tests=$(xml sel -t -v "count(/testsuite/testcase[@status='failed'])" "$surefire_report_path")
          skipped_tests=$(xml sel -t -v "count(/testsuite/testcase[@status='skipped'])" "$surefire_report_path")
          echo "::set-output name=totalTests::$total_tests"
          echo "::set-output name=passedTests::$passed_tests"
          echo "::set-output name=failedTests::$failed_tests"
          echo "::set-output name=skippedTests::$skipped_tests"

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TOTAL_TESTS: ${{ steps.extract-counts.outputs.totalTests }}
          PASSED_TESTS: ${{ steps.extract-counts.outputs.passedTests }}
          FAILED_TESTS: ${{ steps.extract-counts.outputs.failedTests }}
          SKIPPED_TESTS: ${{ steps.extract-counts.outputs.skippedTests }}
        run: |
          slack_message="Results are attached.\n\nTest Results:\nTotal: $TOTAL_TESTS\nPassed: $PASSED_TESTS\nFailed: $FAILED_TESTS\nSkipped: $SKIPPED_TESTS.\n[View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Maven tests completed successfully. $slack_message\"}" "$SLACK_WEBHOOK_URL"
