# File: .github/workflows/maven_test_and_publish.yml

name: Maven Test and Slack Notification v1.0

on:
  workflow_dispatch:
    # Manually trigger the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
     - uses: actions/checkout@v3
    
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

     - name: Run Maven tests
       run: mvn clean test

     - name: Archive test results
       if: always()
       uses: actions/upload-artifact@v2
       with:
          name: surefire-reports
          path: target/surefire-reports

  slack_notification:
    name: Notify Slack on test results
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Function to parse Surefire XML report and extract test counts
          parse_surefire_report() {
            local surefire_report="$1"
            local total_tests=$(xml sel -t -v "count(/testsuite/testcase)" "$surefire_report")
            local passed_tests=$(xml sel -t -v "count(/testsuite/testcase[@status='passed'])" "$surefire_report")
            local failed_tests=$(xml sel -t -v "count(/testsuite/testcase[@status='failed'])" "$surefire_report")
            local skipped_tests=$(xml sel -t -v "count(/testsuite/testcase[@status='skipped'])" "$surefire_report")

            echo "Total tests: $total_tests"
            echo "Passed tests: $passed_tests"
            echo "Failed tests: $failed_tests"
            echo "Skipped tests: $skipped_tests"
          }

          # Path to Surefire XML report
          surefire_report_path="target/surefire-reports/*.xml"

          # Extract test counts
          test_counts=$(parse_surefire_report "$surefire_report_path")

          # Send Slack notification with test counts
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Maven tests completed successfully. $test_counts\"}" "$SLACK_WEBHOOK_URL"
