name: JUnit Slack Reporter with Coverage

on:
  workflow_dispatch:
    # Manually trigger the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
     - uses: actions/checkout@v3
    
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

     - name: Run Maven tests
       run: mvn clean test

     - name: Archive test results
       if: always()
       uses: actions/upload-artifact@v2
       with:
          name: surefire-reports
          path: target/surefire-reports


     - name: Upload JUnit Test Results and Coverage
       uses: neochae1/upload-test-result@v1.0.0
       env:
          JUNIT_TEST_RESULTS: build/test-results/test
          JACOCO_REPORTS: /target/surefire-reports/TEST-TestSuite.xml
          SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            Results are attached.

            Test Results:
            Total: ${{ github.event.pull_request.head.sha }}
            [View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      # - name: Notify Slack
      #   if: always()
      #   uses: rtCamp/action-slack-notify@v2
      #   with:
      #     slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     fields: |
      #       [
      #         {
      #           "title": "JUnit Test Results",
      #           "value": "Results are attached.\n\nTest Results:\nTotal: ${{ github.event.pull_request.head.sha }}\n[View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      #         }
      #       ]
