name: Slack Notification v3.0

on:
  workflow_dispatch:
    # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Using Ubuntu environment for compatibility with xmlstarlet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B test

      - name: Archive surefire test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Wait for report generation
        run: sleep 20s  # Adjust the delay as needed after Maven test completion

      - name: Refresh workspace
        run: |
          git fetch --prune
          git checkout ${{ github.ref }}

      - name: Find generated report
        run: |
          generated_report=$(find ${GITHUB_WORKSPACE}/target/surefire-reports/ -name '*.html' -print -quit)
          echo "Generated Report: $generated_report"
          if [ -z "$generated_report" ]; then
            echo "Error: Generated report not found."
            exit 1
          fi

      - name: Verify file path and existence
        run: |
          ls -l ${{ github.workspace }}/target/surefire-reports/index.html

      - name: Parse test results
        id: parse_results
        run: |
          passed_tests=$(grep -c '<testsuite' target/surefire-reports/*.xml || true)
          failed_tests=$(grep -c '<failure' target/surefire-reports/*.xml || true)
          skipped_tests=$(grep -c '<skipped' target/surefire-reports/*.xml || true)

          echo "Passed: $passed_tests"
          echo "Failed: $failed_tests"
          echo "Skipped: $skipped_tests"

          echo "TOTAL_TESTS=$passed_tests" > results.env
          echo "PASSED_TESTS=$passed_tests" >> results.env
          echo "FAILED_TESTS=$failed_tests" >> results.env
          echo "SKIPPED_TESTS=$skipped_tests" >> results.env

      - name: Set environment variables from results
        run: |
          source results.env

      - name: Test Summary
        id: test_summary
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/junitreports/TEST-*.xml"
        if: always()

  notify-slack:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() }}  # Ensure this step runs after the previous job completes, regardless of its status
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          BUILD_STATUS: ${{ job.status }}
          TOTAL_TESTS: ${{ env.TOTAL_TESTS }}
          PASSED_TESTS: ${{ env.PASSED_TESTS }}
          FAILED_TESTS: ${{ env.FAILED_TESTS }}
          SKIPPED_TESTS: ${{ env.SKIPPED_TESTS }}
        run: |
          slack_message="Results are attached.\n\nBUILD_STATUS: $BUILD_STATUS\nTotal: $TOTAL_TESTS\nPassed: $PASSED_TESTS\nFailed: $FAILED_TESTS\nSkipped: $SKIPPED_TESTS.\n[View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Maven tests completed successfully. $slack_message\"}" "$SLACK_WEBHOOK_URL"
