# File: .github/workflows/maven_test_and_publish.yml

name: Maven Test and Slack Notification v1.0

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  test:
    name: Run Maven Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven tests
        run: mvn clean test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports

  slack_notification:
    name: Notify Slack on test results
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Maven tests completed successfully!"}' $SLACK_WEBHOOK_URL

