name: JUnit Slack Reporter with Coverage

on:
  push:
    branches:
      - main  # Adjust branch as per your requirement

jobs:
  test_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run tests and generate reports
        run: |
          ./gradlew test
          # Adjust paths and commands based on your build system and configuration

      - name: Upload JUnit Test Results and Coverage
        uses: neochae1/upload-test-result@v1.0.0
        env:
          JUNIT_TEST_RESULTS: build/test-results/test
          JACOCO_REPORTS: /target/surefire-reports/TEST-TestSuite.xml
          SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            Results are attached.

            Test Results:
            Total: ${{ github.event.pull_request.head.sha }}
            [View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      # - name: Notify Slack
      #   if: always()
      #   uses: rtCamp/action-slack-notify@v2
      #   with:
      #     slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     fields: |
      #       [
      #         {
      #           "title": "JUnit Test Results",
      #           "value": "Results are attached.\n\nTest Results:\nTotal: ${{ github.event.pull_request.head.sha }}\n[View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      #         }
      #       ]
